### ISSUE TITLE
image editor fill bug

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#1939]
## Problem description

Using the fill bucket tool leaves pixels not filled in places.

![imageditorbug](https://user-images.githubusercontent.com/30123541/44420776-c08d2680-a576-11e8-9c95-bc9811c7e69f.gif)

## Attach a .c3p

n/a

## Steps to reproduce

just open image editor from double clicking a sprite object. I resize the canvas, then just select pencil draw a shape then select fill and try to fill it.

## Observed result

leaves some pixels unfilled.

## Expected result

should flood fill.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_4
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r104 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 88 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Assigning to Diego to check, but:

> C3 release: r104 (stable)

This is 10 releases behind the latest beta. Please only check the latest release to ensure you don't report bugs that are already fixed.

**Comment by mOOnpunk** [comment]
Well i have to use r104 as using c3 at the moment is like picking a version with least annoying bugs. Latest stable has cpu bug and auto save bug, and i try to avoid beta with my project. You should maybe release a new stable then, and test it more first for bugs?

**Comment by AshleyScirra** [comment]
All you need to do is try to reproduce it in the latest beta.

**Comment by DiegoScirra** [comment]
Can't reproduce this one in either r104 nor r114, maybe it's OSX only?

**Comment by mOOnpunk** [comment]
The bugs still there in Beta R114. It would be nice at some point to be able to continue with actually making my game. Every release lately prevents me from doing it, stable or beta.

Anyway, It only appears to happen when you resize to certain dimensions, i can reproduce the bug at 450x300 every time.

**Comment by DiegoScirra** [comment]
Can you post the image you are using?

**Comment by mOOnpunk** [comment]
Hi, It happens when i draw any image.

I've done another recording and the saved the image i drew.

![animation 1](https://user-images.githubusercontent.com/30123541/44926380-22087e80-ad49-11e8-91ad-98f293631ff3.png)

![aug-31-2018 18-07-11](https://user-images.githubusercontent.com/30123541/44926386-259c0580-ad49-11e8-80a1-41ccad9a3839.gif)

**Comment by AshleyScirra** [comment]
Is this still an issue in the latest release? It's marked 'can't reproduce' and has had no activity for ~6 months.

**Comment by LukeNecklace** [comment]
Just testing this for you guys.

I just replicated this bug.

This might be overkill, but doing this gave me the same result twice.

1) insert sprite object
2) Make sure your "toggle background brightness" is set to white
3) Draw something so it is a whole like in the video shared above. Do not change colours. Just use the default black and white colours that construct gives you when you first open the image editor.
4) fill it with black
5) Press Cntrl + Z
6) Resize to 400 x 300 (or some large scale)
7) Fill the image with black.

**Observed result:** 
It will not fill the whole image.

Also if you do this step afterwards:

8) You'll see how strange the image saves. It looks nothing like what you see in the image editor before closing it.

https://www.dropbox.com/s/p3ao4ne9zriear9/image%20editor%20fill%20bug.c3p?dl=0

When you open the project, you can see immediately just how strange some of the sprites have turned out just from doing this.

**Comment by DiegoScirra** [comment]
@LukeNecklace

That is not a bug, the fill tool finds all adjacent pixels of the same color as the one you clicked in, until it can find no more or the image is filled. If you click on a white pixel it will attempt to change the color of all surrounding white pixels, until it finds a boundary of a different color. That is what is happening in your examples.

As for the original issue, I was never able to reproduce it and don't have any leads as to what the cause might be.  Closing it.
