### ISSUE TITLE
Fullscreen not working in Runtime 3, r115 beta

### ISSUE THREAD

**Issue by dolomite** [Scirra/Construct-3-bugs#2018]
## Problem description

The request for full screen is not properly working on runtime 3, r115b. When fullscreen is requested, the window goes to full screen but the actual game area does not resize and stays at the top left corner of the screen. However, when switched back to runtime 2, the full screen works normally again.

## Attach a .c3p

[full_screen_test-2.zip](https://github.com/Scirra/Construct-3-bugs/files/2365550/full_screen_test-2.zip)

## Steps to reproduce

1. The project should be set to runtime 3. Run the game.
2. Hit the Q key on keyboard to jump to full screen.
3. In runtime 3, the window goes to full screen but the game render area doesn't get resize.
4. Exit game by ESC. change to runtime 2 and run the game.
5. The game is now in full screen.

## Observed result

The window expands into full screen but the actual game area does not resize.

## Expected result

The window expands into full screen and the game area also resizes to fit the full screen also - like in runtime 2.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r115 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 22 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is another case of #198. "Centered" fullscreen mode is not actually meant to stretch the game (hence the fact it doesn't use the term "stretch" in the name unlike all the other options), but it doesn't actually center in the C3 runtime, which is fixed in the next release.

**Comment by dolomite** [comment]
I just tried with r116 and while it does centers the game in fullscreen mode, it still doesn't resizes to full screen. So does that mean that fullscreen functionality is just not activated on runtime 3 then?

**Comment by AshleyScirra** [comment]
"Centered" mode does not resize the game. That's why it doesn't have "Stretch" in the name, like all the other options.

**Comment by dolomite** [comment]
Ok i see what you mean now.
