### ISSUE TITLE
The image editor is glitchy...

### ISSUE THREAD

**Issue by johnsmith27** [Scirra/Construct-3-bugs#2405]
## Problem description
From time to times, editing an animation gives weird results. It seems fine in the editor, but once you leave it (or switch to a different frame and then switch back to the edited frame), you end up with weird graphic glitch like missing pixels, or added black pixels, which can be really annoying.

Seems to happen mostly when I delete pixels with the pencil tool (right click set to 0% alpha) or when using the selection tool to move/cut/copy/paste stuff around.

## Attach a .c3p

https://www.dropbox.com/s/c8yzymxatm2i02o/editor_glitch.c3p?dl=0

## Steps to reproduce

Edit the "sprite7"
use the pencil, pick one of the existing color and add some pixels on the first frame. then go to the next frame, remove the black pixels (which I did not add, it's the result of the explained problem above).  Close image editor and re-open it.

## Observed result

The newly added pixels have disappeared, while the black ones are still there...(though maybe a bit different)

## Expected result

Added pixels should remain while deleted ones should be gone.

## Affected browsers/platforms

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 94 mb (0.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next release

**Comment by johnsmith27** [comment]
Great, thanks !

**Comment by johnsmith27** [comment]
Not sure if it's supposed to be fixed in R131 but it's still happening on this release... (only noticed when using the selection tool to move pixels (resulting in erasing them instead of moving them) )

**Comment by johnsmith27** [comment]
Still happening with 142.2...
Image editor is still glitchy to the point I'm afraid to use it now.

Mostly the selection tool with cut/copy/paste &/or simply moving
But also with drawing, although pretty rare, only happened to me once (with the pencil) since R131 but it was not nice to see my work completely gone as you can imagine.

I may be wrong but both problems feels like they're mainly due to animation and frames switching (and maybe by using the shortcuts ctrl+arrows as this is what I usually use). 
Way less problems with non-animated sprite although the selection tool always feel insecure to me and I use it carefully..

Should I open a new thread or is this one still okay ?
