### ISSUE TITLE
Webgames made with C3 not working on android using chrome browser

### ISSUE THREAD

**Issue by MonDieu72** [Scirra/Construct-3-bugs#2650]
## Problem description

Webgames made with C3 that are run on android devices using the chrome browser only shows the grey background, all other graphics are gone. Same game runs fine on the same device when run in firefox browser. Game also runs fine on iOS with Safari, Chrome and Firfeox. Web games made with other game engine works fine with both chrome and firefox browsers on android & iOS. I only have samsung devices but yesterday they all played the games fine with the chrome browser but today none of them do.

## Attach a .c3p
https://1drv.ms/u/s!AjgxVO4vN9p6g91wyAZLG87p5557qg

## Steps to reproduce 

1. Export webserver using html5 exporter or use remote testing.
2. Try to run the game on an android device using the chrome browser.
3.

## Observed result

Game only shows background without any graphics

## Expected result

The game to play normally

## More details
This very much reminds me of the webgl problem we had some time ago.. last year I think it was.

**Affected browsers/platforms:** 
Chrome on Android (perhaps only samsung)
[Endless Runner Prototype.zip](https://github.com/Scirra/Construct-3-bugs/files/2898097/Endless.Runner.Prototype.zip)

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you provide a link to where you have published the game? These issues often come down to upload errors or server configuration issues.

**Comment by MonDieu72** [comment]
I put it on my website at: https://techboxnorth.com/runner/
also have a flappy game up there at https://techboxnorth.com/flip/ that worked fine a few days ago

**Comment by MonDieu72** [comment]
Some times they work properly and some times (like 75%) all I get is the grey background. Sound is still there (in the flappy game)

**Comment by shortercode** [comment]
@MonDieu72 what chrome version is the device running? A quick check on a Samsung tab and a Pixel 2 show the runner game to be working.

**Comment by MonDieu72** [comment]
Samsung Galaxy S7 (SM-G930F) => chrome version 72.0.3626.105, Android 8.0.0
Samsung Galaxy Tab S  (SM-T805) => same chrome version , Android 6.0.1
Have you tried starting the runner game while holding the phone in portrait orientation? That always gives grey screen on both these devices

**Comment by shortercode** [comment]
I have only tried in portrait so far, both devices were running the same Chrome version. The pixel was running Android 9 and the tab Android 5. Will try our S8 in a moment, closest we have to a S7 in the office.

**Comment by kingpirux** [comment]
this is seems the same problem i published https://github.com/Scirra/Construct-3-bugs/issues/2643 the background color covers all, its an issue that started in 137

**Comment by shortercode** [comment]
I've tried installing it to the homescreen and can see the issue now, although it doesn't appear to require rotation. Just looking into it now

**Comment by shortercode** [comment]
I have managed to reproduce it in browser as well now, unfortunately it doesn't seem to produce an any errors, it just stops rendering. This might be related to the webGL 2 errors, but this will be the first time we've had that issue in the browser.

**Comment by shortercode** [comment]
Checked the spec sheet for the Nokia 3 as per #2643 and it contains a Mali-T720MP1

**Comment by kingpirux** [comment]
This issue started from r137, in r136 it works perfectly. It is caused by: Changing orientation and Fullscreen.

**Comment by kingpirux** [comment]
PD: I dont think is stopping rendering, it still rendering but it paints all with the background color, because some times while you change orientation you can see everything in the game for a second while it is changing orientation. And everything else works normally like sound and collisions.

**Comment by MonDieu72** [comment]
So once again we need to go back to webgl 1?

**Comment by AshleyScirra** [comment]
I think this is another case of driver bugs killing WebGL 2 on Mali GPUs. I've reimplemented the WebGL 2 bypass for Android in the next release, but this time specifically targeting Mali GPUs (so at least Adrenos + others can keep using WebGL 2). This makes Android devices with Mali GPUs drop back to WebGL 1 where everything seems to keep working OK. Marking to verify when the next release out since it depends on specific devices.

**Comment by MonDieu72** [comment]
Just to make sure I understand: will that bypass work when game is played on a website with the chrome browser on these devices as well as when exporting to android?

**Comment by AshleyScirra** [comment]
Yes, the bypass happens with any exporter on an Android device with a Mali GPU.

**Comment by kingpirux** [comment]
just to add information, it sometimes works fine when reload the web, but in apps since you cant reload without exit it is imposible to do that fix.

**Comment by kingpirux** [comment]
I keep testing because my project needs it and it was updated to this bugged beta version (my bad) I found a way for mitigating the bug with "Max spritesheet size" at maximum, running it in chrome in the correct position (landscape) it works fine everytime, no problem at all (you can even change orientation once running) but if you start the app in incorrect position (for example portrait if it was landscape) it always fail, with Max Spritesheet size in other value, some times it fails and some times it wont, im pretty sure this is related also with my project size so try it with a large project.

Also once it fails, if you turn the last layer in transparent, you can see a pixel in the top corner changing colors according to what it should be showing.
Hope this gives a clue or something :+1:

**Comment by AshleyScirra** [comment]
For the record we're following this up with Google in this report: crbug.com/934823

It does look like rotating the device contributes to causing it, and it affects both the Chrome browser and the webview (I've reproduced both on a Samsung Galaxy Tab S2). The next release disables WebGL 2 on Mali devices so hopefully this will work around the problem entirely.

**Comment by cmr333** [comment]
Hi, I've been having a very similar problem for my android app, I released an update to my game last week (R138) (also today R139) and I've did a bit of marketing because I started a special event with my game and I've gained about 300 new users but unfortunately about 10 of those users (different phones, versions and specs and screen size, new and old etc) have been complaining that all they see is a white screen.

One of the users showed me a video and it seems like the graphics won't load on their game, the colours they see are the layout colours I've set for the layers. Sound works as well as actually touching the screen, so they can technically control the main character and interact with the menu but all they see is a white screen, it's like playing with your screen turned off.

I've spent this entire week trying to figure out the problem but I am completely lost and I believe it's out of my control and it's a problem with the game engine or chrome or the export.

I use the construct 3 runtime and android signed apk export.

Unfortunately I don't have a phone that has this problem so I have to keep guessing what's causing the problem, I've given up until I read this post just now.

**Comment by SnipG** [comment]
If Scirra has free devices to root, you guys could maybe to fast check with Mali Gpu debugger:
https://youtu.be/yv-V9Bl9pO4?t=160
I don't want to root my device, but it bugs with  browser version of bug example. It starts to load it for few frames then screen turns back/white depending on background color and only after few resizes it starts to show spinning box again. 
Chrome ppl might not fix it.

**Comment by AshleyScirra** [comment]
Non-deterministic GPU driver bugs are an absolute nightmare. We could easily spend a week digging in to this and get nowhere. It's simply too costly. If Google or Mali engineers won't look in to it, the only feasible option is to disable it and move on.

**Comment by cmr333** [comment]
Thanks for your hard work Scirra team.

**Comment by SnipG** [comment]
I  used phone that fails all thous examples, so i went to try out babylon js examples and they also fail hard with this mali phone.
https://doc.babylonjs.com/examples/
Example skull -> will bug out and dissappear.
Example Cell shading -> the cells dissappear after few moves.
Non of thous behavior occur on pc or my Adreno phone. So its not your engine problem only :)

**Comment by AshleyScirra** [comment]
@SnipG - yes, please mention that information on the [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=934823), including the specific device models that are affected/not affected.

It's not clear whether those demos use WebGL 1 or WebGL 2, but if it's a Mali-specific glitch it might be relevant anyway.

**Comment by AshleyScirra** [comment]
r140 is now out, please check again!

**Comment by cmr333** [comment]
I published a patch to my game on Android with R140 and so far two users who had a problem with my game reported back saying that it works now.

**Comment by MonDieu72** [comment]
re-upped one of my webgames exported with r140 and so far everything looks normal again :)

**Comment by AshleyScirra** [comment]
Thanks for confirming.

**Comment by kingpirux** [comment]
the bug is back in r143. Is better than before, it doesnt happen all the time, but it happends.
