### ISSUE TITLE
[Desktop] Construct 3 beta channel fails to run offline

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2672]
## Problem description
The beta channel version of Construct 3 desktop fails to run if there is no active internet connection. This makes it impossible to use Construct 3 offline and continue working on projects.

## Steps to reproduce

1. Download most recent version of [C3 desktop](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-3-desktop-build-beta-131317#forumPost923348) (_construct3-win64-c71-beta-2_)
2. Run it once and wait until notification that "offline use is ready" is shown
3. Close it and disconnect from the internet
4. Run it again and notice that the process starts in the background but nothing else happens

## Observed result

The beta channel version of Construct 3 desktop doesn't run in offline mode. 

This is most-likely because NW.js cannot open up "https://editor.construct.net/beta", in order to perform the switch to the latest available beta version.

## Expected result

I should be able to work offline using the beta channel of Construct 3 desktop.

## More details

**Affected browsers/platforms:**  NW.js (Windows 7)

**First affected release:** r139 beta

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r139 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 288 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This has been a known issue since the desktop version was released. Will leave this issue though as a reminder that we might want to figure out a way to do the beta redirect offline.

**Comment by AshleyScirra** [comment]
This should now be working. It has involved a server-side update, so you may need to clear your cache, but we now have an offline-capable redirect at editor.construct.net/beta that redirects to the last used beta release if you're offline. This only works with r153+ since it has new code to remember the last used beta release, but I've tested it and verified it appears to be working, so beta releases should continue to work as expected offline now, in both desktop and as PWAs.

**Comment by TheRealDannyyy** [comment]
@AshleyScirra Request to open this issue again.
I've tested this with the most recent beta (construct3-win64-c77-beta) and it just ends up running in the background again. As soon as I enable connect to the Internet again, it stops running in the background and everything works as expected. It's still not possible to run C3 Desktop beta offline.

I'm not sure if it's worth investigating since it's going to be deprecated next year, just felt like mentioning it.
