### ISSUE TITLE
SpriteFont TextWidth not using widths set with "Set Character Width"

### ISSUE THREAD

**Issue by ariepert** [Scirra/Construct-3-bugs#2897]
## Problem description

SpriteFont does not use character widths set with "Set character width" when calculating TextWidth, although the font does display properly. At first I thought it wasn't centering the font properly and having issues with word wrap, but then I realized it was using the default character width, not the set widths.

## Attach a .c3p

[https://www.rieperts.com/games/forum/TextWidthError.c3p](url)

## Steps to reproduce

1. run the file

## Observed result

C3 reports a TextWidth of 305, which is 5 x 61 (the default character width)

looping through each letter of the text does give the correct character width, but TextWidth is incorrect.  The font is spaced correctly, but it is not centered in the area I expected because it is using an incorrect TextWidth.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.103
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
C3 release: r146 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 674 mb (4.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It looks like this only affects imported C2 projects - it works correctly in the C2 runtime, and in the C3 runtime you can use character spacing in the editor with the new spacing property, rather than setting it in events, and you don't need to wait to get the textwidth/textheight.

It turns out this only happens with the 'Set character width' action in the C3 runtime, which is fixed for the next release. If you use the built-in spacing feature it should work OK already.

**Comment by Magistross** [comment]
Bumping this issue as I stumbled onto something related. It seems the 'Set character width' action is still buggy regarding the space character. The action is completely ignored.

Character spacing in editor do work for the space character though.

**Comment by AshleyScirra** [comment]
This issue was closed in April. Please file a new issue following all the guidelines if you still have trouble.
