### ISSUE TITLE
Android App freezes when returning from background

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3414]
## Problem description

After switching apps, or using the Home button, and then returning to the app it is frozen.

## Attach a .c3p

https://drive.google.com/open?id=1HcZ-wNFOjJSevXjX39FHtOHAzHlSSMPW

## Steps to reproduce

1.Export to Cordova Android debug, dedupe images, advanced minification, and require local storage, 5.0 + using C3.
2.Install debug apk
3.Run app
4.Switch, or leave app using Home button.(closing app works as expected)
5. Return to app after 5 to 10 minutes

## Observed result

App is frozen to last frame observed.
App will not resume.

## Expected result

App resumes as when refocused.

## More details

**Affected browsers/platforms:** Android 5.0.2 

**First affected release:** C3 Beta release 170.2 to unknown
Debug Apk: https://drive.google.com/open?id=1jivfnlKK6AyA4hSt4g76NoFN7CDd5BXM

## System details
Exported W10 Chrome

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It is generally infeasible to investigate reports which include steps like this:

> Return to app after 5 to 10 minutes

Typically this means you are actually doing something else which really causes the problem, but you haven't identified what that is yet. Further, since it's not uncommon to have to follow the steps dozens of times while investigating it, a step like that makes it take so long to investigate as to be infeasible to fix, *especially* since a fixed time limit is not specified. For example if we wait 5 minutes and then do not reproduce the issue, is it because the device is not affected, or because we did not wait long enough? If we wait 10 minutes and it does not reproduce is it because the real amount of time you have to wait is actually 15 minutes? etc. This kind of ambiguity basically makes it infeasible to investigate the issue.

So can you find a way to more reliably reproduce the problem with no waiting or variation in the steps to reproduce? It's very likely we will need that to be able to investigate.

**Comment by pigmalien** [comment]
Waiting is the one step. I can replicate it after exactly 5 minutes. It does not happen at 4.
No other steps are necessary. No need to start any other process. Start the app, minimize it using the Home button, return to it using app icon, or app launcher.

Phone specs are:
Processor: Quad-core, 1200 MHz, ARM Cortex-A53, 64-bit
Ram: 1 gb
Gpu: Adreno 306

**Comment by NetOneGames** [comment]
Yea I am finding this also with the app I just submitted to playstore.
**Definitely is appears to be about how long the app was suspended.**
I havent make APK before so i though I might be doing something wrong but the app is so simple there is nothing to really to go wrong.
I will try to do some experiment this week.

**Comment by Boulerzzz** [comment]
I also got loads of mails and 1 star feedback from user complaining about this and I could reproduce it in every single C3 game I have for android. but didn't know how to solve it.

Got so tired of it I just decided to kill the app whenever it's suspended. 🤣 
Just make sure not to kill it when your performing something in game that puts your game in background such as performing an IAP or showing an ad/leaderboard etc. But if the game is simple the game should start really quickly even from a cold start so no user will really notice anything.

**Comment by NetOneGames** [comment]
tested with a few simple apks, so yea this is pretty consistent, even making an apk with default 1080 portrait project and simple rotating box.  The time seems to vary though.   The wait makes it really hard to test.  Can be anything form 5 to 20 minutes it must have something to do with what the phone is doing to apps that are in the background the longer suspended the more likely they are to freeze.  But they will always all freeze at some point.

**Comment by AshleyScirra** [comment]
It would be helpful if you can connect USB debugging and see if any errors appear in the console when it fails to resume.

**Comment by NetOneGames** [comment]
I dont know how to do that,  but I will have a look tonight.  Is that through android studio?

**Comment by AshleyScirra** [comment]
See here: https://www.construct.net/en/tutorials/checking-for-errors-in-browsers-5

**Comment by Boulerzzz** [comment]
I debugged with my phone connected a few days ago to see if I would find anything. Didn't know what to look for though but I did copy what I saw in the debugging tab when the app froze.

But like I said I was not sure what to copy really...

W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:13.987061, limit is:60The moving distance of Y is:134.9375, limit is:60
D/CordovaActivity: Paused the activity.
D/ZrHung.AppEyeUiProbe: stop checker.
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
D/ViewRootImpl[MainActivity]: surface should not be released
D/CordovaActivity: Stopped the activity.
W/libEGL: EGLNativeWindowType 0x73de750010 disconnect failed
D/SystemWebChromeClient: file:///android_asset/www/scripts/c3runtime.js: Line 2 : [Construct 3] Suspending
I/chromium: [INFO:CONSOLE(2)] "[Construct 3] Suspending", source: file:///android_asset/www/scripts/c3runtime.js (2)
W/chromium: [WARNING:sync_reader.cc(170)] ASR: No room in socket buffer.: Broken pipe (32)
D/: PlayerBase::stop() from IPlayer
D/AudioTrack: stop() called with 6465600 frames delivered
D/ZrHung.AppEyeUiProbe: Current Activity:false
not watching, wait.
E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
D/: TrackPlayerBase::~TrackPlayerBase()
PlayerBase::~PlayerBase()
D/CordovaActivity: Started the activity.
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: restart watching
D/CordovaActivity: Resumed the activity.
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time
W/InputMethodManager: startInputReason = 1
W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:65.04089, limit is:60The moving distance of Y is:34.6687, limit is:60

**Comment by AshleyScirra** [comment]
That looks like the Android system log, and I can't see anything directly relevant in it. The tutorial I linked to shows how to get the Chrome browser log which is what I was after.

**Comment by NetOneGames** [comment]
right i see, cheers Ashley, cant have a look till tonight, but will get back ASAP (unless someone figures it out in the meantime).

**Comment by AshleyScirra** [comment]
I can reproduce. It looks like it's not firing a resume event after suspending, so it hasn't crashed, it's just left suspended. I've no idea why and the long repro steps will slow down investigation, but I'll see if I can figure out what's going on...

**Comment by AshleyScirra** [comment]
Alright, think I figured out what's going on, looks like a bug in the Chrome webview. I guess it was introduced in a recent update since nobody reported this until recently. I've got a change that I think works around the bug and we should have a stable patch out soon for a couple of other issues too. Given the difficulty in testing marking this for checking again after next release.

**Comment by Boulerzzz** [comment]
Thanks you so much Ashley!
I think it's recent too because I have many thousands of daily active users I got my first reports about this only last week.

**Comment by NetOneGames** [comment]
Nice.
My app is currently under review maybe the testers will pick it up.

**Comment by AshleyScirra** [comment]
This should be working now in r171.2. Can anyone confirm it is solved for them too?

**Comment by NetOneGames** [comment]
(just discovered the awesomeness of downloading c3p from cloud, and building an apk from a mobile phone pretty damn cool there cant be many game dev software that can do that)
anyway.
Did a **30 min test** on an apk that usually fails within 10min.  
**and resumed no problem.** 
**Will do a final check** and leave a bit longer (maybe an hour +) just to make sure but yea looks good so far.

**Comment by NetOneGames** [comment]
Can I just ask if back button pressed should app go into suspend? or is there specific events?  I do have on back button > blur in events but that was for web version or does that work on app as well?

**Comment by AshleyScirra** [comment]
Nobody mentioned the back button before in this issue, and none of the code related to that has changed recently, so no, there have not been any intentional changes to that. This issue relates only to whether the game can properly resume after returning to the app.

**Comment by AshleyScirra** [comment]
OK, thanks for confirming! Closing as all indications are this is fixed.

**Comment by NetOneGames** [comment]
Ashley I think this is back ......

**Comment by AshleyScirra** [comment]
The original report was Android-specific and was closed based on evidence the issue was resolved. If there is a problem with a different platform it is likely unrelated, so please file a new report following all the guidelines again.

**Comment by coderGtm** [comment]
I face this issue in my Android app while using a webview. And reading from the logcat, the only unusual thing I see is this:
`W/chromium: [WARNING:sync_reader.cc(237)] ASR: No room in socket buffer.: Broken pipe (32)`
Though I am not using sockets in that html page.

Above reply also had the same line

> I debugged with my phone connected a few days ago to see if I would find anything. Didn't know what to look for though but I did copy what I saw in the debugging tab when the app froze.
> 
> But like I said I was not sure what to copy really...
> 
> W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:13.987061, limit is:60The moving distance of Y is:134.9375, limit is:60 D/CordovaActivity: Paused the activity. D/ZrHung.AppEyeUiProbe: stop checker. I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time D/ViewRootImpl[MainActivity]: surface should not be released D/CordovaActivity: Stopped the activity. W/libEGL: EGLNativeWindowType 0x73de750010 disconnect failed D/SystemWebChromeClient: file:///android_asset/www/scripts/c3runtime.js: Line 2 : [Construct 3] Suspending I/chromium: [INFO:CONSOLE(2)] "[Construct 3] Suspending", source: file:///android_asset/www/scripts/c3runtime.js (2) W/chromium: [WARNING:sync_reader.cc(170)] ASR: No room in socket buffer.: Broken pipe (32) D/: PlayerBase::stop() from IPlayer D/AudioTrack: stop() called with 6465600 frames delivered D/ZrHung.AppEyeUiProbe: Current Activity:false not watching, wait. E/: [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008] D/: TrackPlayerBase::~TrackPlayerBase() PlayerBase::~PlayerBase() D/CordovaActivity: Started the activity. D/ZrHung.AppEyeUiProbe: notify runnable to start. D/ZrHung.AppEyeUiProbe: restart watching D/CordovaActivity: Resumed the activity. D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000 I/ViewRootImpl: jank_removeInvalidNode all the node in jank list is out of time W/InputMethodManager: startInputReason = 1 W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:65.04089, limit is:60The moving distance of Y is:34.6687, limit is:60

SO I suspect it's still not resolved
