### ISSUE TITLE
Crash when previewing a video

### ISSUE THREAD

**Issue by Souls3** [Scirra/Construct-3-bugs#3452]
## Problem Discription

Sometimes when I upload .mp4 or .webm file, Construct crashes when previewing them.

## Attached Project

[Test Video.zip](https://github.com/Scirra/Construct-3-bugs/files/3788946/Test.Video.zip)

## Steps to Reproduce

1. Add a Video plugin
2. Import a .mp4 video
3. Set the Video H.264 source property to the video name (Either I write the extension in the name or not, the result is the same)
4. Double click the video in the videos folder
5. Construct shows the dimensions are ? x ?, and keeps loading the video forever
6. Click on the preview screen a few times

## Observed result

Video not showing when I run the project
Endless loading in preview
Crash
(I tried multiple times, it only worked fine once or twice)

## Expected result

Video should load in the preview and when I run the project

## More details

**Affected browsers/platforms:** Firefox

**First affected release:** r171.3

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled rejection
Reason: Error: The fetching process for the media resource was aborted by the user agent at the user's request.
Construct 3 version: r171.3
URL: https://editor.construct.net/
Date: Wed Oct 30 2019 14:37:47 GMT+0200 (Eastern European Standard Time)
Uptime: 16984.4 s
Platform information

Browser: Firefox
Browser version: 70.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
C3 release: r171.3 (stable)
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA Quadro 600 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this - I tried using Firefox 70 on Windows 10 64-bit and the project worked fine. The video shows the correct dimensions, the video plays, and there is no crash using the video preview controls or closing the dialog.

Can you reproduce this using Firefox Nightly? It might be a Firefox bug that was already fixed.

**Comment by Souls3** [comment]
Thanks. I could reproduce it hundred times when I wrote this, but once I restarted my PC it didn't happen again.
Will update if it occurred again.

**Comment by Souls3** [comment]
Update:
Tested on Firefox 70.0 and Chrome 78.0.3904.87 (Official Build)

[Test Video Mp4.zip](https://github.com/Scirra/Construct-3-bugs/files/3801444/Test.Video.Mp4.zip)

Firefox: Video doesn't show in web preview
Chrome: Video shows up and has sound in web preview

Exporting to Desktop (NW.js). Tested from both browsers, same result:
The video shows up, but has no sound
The video is mp4.

In another project, I had mp3 sounds. They didn't run in NW.js, until I used a webm version instead.

**Comment by Souls3** [comment]
Update
Converted video to webm. Works with sound in NW.js export, but still not showing when I click preview in browser, and still doesn't show when I double click the video (Video preview)

**Comment by AshleyScirra** [comment]
I still cannot reproduce this. Please test Firefox Nightly like I suggested, or we cannot make progress on this issue.

**Comment by Souls3** [comment]
[Test Vid(2).zip](https://github.com/Scirra/Construct-3-bugs/files/3808991/Test.Vid.2.zip)
Tested this on Nightly (72.0a1 (2019-11-04) (64-bit)) and Chrome (Same 78.0.3904.87 (Official Build)). Nightly is fresh with no extra addons or anything.
Added a log message when the video is playing (Video-Is Playing::Browser-Log).

Chrome: works fine when I click Play, video and log message shows up.
Nightly: doesn't work when I click play, no video and no log message, so the video is not even playing.
Clicked on the page's permissions icon and made sure Autoplay is set to "Allow Audio and Video".
When I debug the project and click on the video object in the debug menu, a highlighted rectangle shows around where the video is supposed to be, but the video itself is still invisible.

Double clicking the video in the project window shows the preview window, and it is working fine.

**Comment by AshleyScirra** [comment]
It appears you are describing a different problem now.

The original report was: the editor can't play the video, and crashed

The new report is: the editor **can** play the video, but the runtime can't play the video

Is this right? It quickly becomes very confusing if you start talking about a different problem to the original report. It might be worth starting over at this point with the latest issue, if the original issue is no longer occurring.

**Comment by AshleyScirra** [comment]
I can reproduce the issue with the video not playing at runtime in Firefox, but as far as I can tell all our code is correct and Firefox gets stuck loading the video. It works correctly in Chrome and Edge, pointing to a bug in Firefox. It also works correctly in Firefox after export, so it's only a problem with preview mode.

This means regardless of which bug you are talking about there is no action we can take:
- editor issue: can't reproduce
- runtime issue: appears to be a Firefox bug

Therefore closing this issue as there is nothing we can do about it. If you still want to try and get the video working in preview in Firefox you could try reporting it as a Firefox bug.
