### ISSUE TITLE
Construct 3 Desktop Stable - Onedrive Cross-Origin Read Blocking (CORB) 

### ISSUE THREAD

**Issue by luisforte** [Scirra/Construct-3-bugs#3584]
## Problem description

Cloud Onedrive log-on but cant refresh files-list

## Attach a .c3p

Just log-on Onedrive and try to see files list

## Steps to reproduce

Click save -> Cloud -> Onedrive -> put credencials and log-on -> try to see files list

## Observed result

Error - Failed to refresh File List

## Expected result

My Project files

## More details

![1](https://user-images.githubusercontent.com/20118021/72226713-da1b7d80-3572-11ea-8557-1f33bcf7390c.jpg)

**Affected browsers/platforms:** 

**First affected release:** r171.3 stable

## System details

<details><summary>View details</summary>

Full console:
![image](https://user-images.githubusercontent.com/20118021/72226740-22d33680-3573-11ea-975a-df1a0f389851.png)

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. I would guess the error is caused by something else. If you clear your browser cache/cookies and log in again does it work?

**Comment by luisforte** [comment]
Browser cleaned and problem still
and stucket loggedIn
![image](https://user-images.githubusercontent.com/20118021/72227632-c88ba300-357d-11ea-9426-9752b92a6011.png)

i tried disconecting from microsoft account and change password but nothing log-out from C3... sinister

i will still using the web version for now....

**Comment by AshleyScirra** [comment]
> i will still using the web version for now....

Were you using the desktop download? Please always include your full system information as per the bug report guidelines, it helps answer questions like this and avoid confusion.

**Comment by luisforte** [comment]
sorry for this Ashley i forgot this detail...

**Comment by AshleyScirra** [comment]
@luisforte I was asking for the information, not for the issue to be closed. However this sounds like an issue we already fixed a long time ago. Please make sure you are using the latest version of the desktop download. The reason I asked for that information is it would indicate which version of the desktop download you are using.

**Comment by luisforte** [comment]
I said the version here > "First affected release: r171.3 stable"
forgot to mention its DESKTOP version...
i cant fully clean my browser because my workplace and delayed work.
Need to re-open the issue ? i dont believe i an the only one getting this trouble.

**Comment by shortercode** [comment]
The platform information text includes the version of your nwjs wrapper. I
believe that is what is out of date in this case.

**Comment by luisforte** [comment]
Formated PC and error still..
![image](https://user-images.githubusercontent.com/20118021/73250871-8b86f980-4196-11ea-85c2-4ddf382fb926.png)
Construct DESKTO PBUILD r182.2 STABLE

**Comment by AshleyScirra** [comment]
Please file a new bug report following all the guidelines, including your system information - which still has not been provided in this report at any point - otherwise we cannot help you.
