### ISSUE TITLE
iPadOS 13.4 - Can’t Left Click in Construct

### ISSUE THREAD

**Issue by HammerFox** [Scirra/Construct-3-bugs#3729]
## Problem description

Real mouse support was added to iPads with the just released iPadOS 13.4. I am well aware that this isn't a big deal for many, but I've really been wanting to use my iPad in place of a laptop, and Construct 3 is one of my last hold outs. The issue here is that left clicking simply doesn't work on iPadOS when using Construct. Right clicking does, but you can't even click any of the options within the menu. This is likely due to how Apple botches PWAs or some other obscure issue out of your folks' control, but I figured I'd ask about it here anyhow. 

## Attach a .c3p

Construct 3/iOS PWA issue

## Steps to reproduce

1.Use iPadOS 13.4 and access Construct through Safari

## Observed result

Cannot left click on most UI elements.

## Expected result

Functional Left Clicking

## More details
It previously worked with iPadOS when mouse support was just an Accessibility feature, but I assume that’s because iOS just treated clicks as a normal touch event. You can click on things like the Open and New Project buttons, but you can’t click the options in the “Open” drop-down menu, but you can click on options in the window that pops up for “New Project” where you set your project’s initial settings. Like the drop down menus and the Create/Cancel buttons in the window.

**Affected browsers/platforms:**
iPadOS 13.4

**First affected release:**

## System details

<details><summary>View details</summary>

Platform information
Browser: Safari
Browser version: 13.1
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: iOS
Operating system version: 13.4
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPad; CPU OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 511
Extensions:

EXT_blend_minmax
EXT_sRGB
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_depth_texture
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)

</details>

**Comment by AshleyScirra** [comment]
Ugh, more iOS compatibility nonsense. What device are you using as a mouse exactly? We'll probably have to order in equivalent kit.

**Comment by HammerFox** [comment]
I apologize. I'm mainly using a Logitech M720 Triathlon, but it also happens with my other Bluetooth mice as well. I really don't think it's the mouse, but Apple's strange implementation of mice itself. Google Drive is one web app that works flawlessly, but I understand that's not an apple to apple comparison, and it's definitely not your fault that Apple handles web apps like they do.

**Comment by AshleyScirra** [comment]
Alright, my bluetooth mouse arrived and was able to test this. We had some old backwards compatibility code for, um, iOS, that was blocking this. So I took that out and it works again. I'm not sure if that will regress other features of iOS that were fixed by putting that in there in the first place, but... I guess we'll find out.

**Comment by HammerFox** [comment]
Is the fix in r194 beta? I updated to that and it still doesn't seem to work.

**Comment by AshleyScirra** [comment]
No, this change came after the last beta. In general if it's not in the changelog, it wasn't changed in that release.
