### ISSUE TITLE
Form Control object blocking keyboard events

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3907]
## Problem description

This is an old and known issue.. After clicking a button or moving a slider bar, keyboard events are not working.
With buttons I can add "Button set unfocused" (which is still a nuisance), but this doesn't work with checkboxes and sliders.

## Attach a .c3p

https://www.dropbox.com/s/v1m5xci8mofxweb/FormControlsKeyboard.c3p?dl=0

## Steps to reproduce

Move a slider or click the button and try typing something.

## Observed result

Keyboard events are not triggered because form control retains focus.

## Expected result

Keyboard should work.

## More details

**Affected browsers/platforms:**  All
**First affected release:** All

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r201 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 426 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is actually a regression in the C3 runtime - the C2 runtime correctly restores focus to the game when you click off a form control, but that code never made it across to the C3 runtime. I ported it across and it works as expected again, so it should be fixed in the next release.

**Comment by dop2000** [comment]
Hi @AshleyScirra , Does this mean that keyboard will not work, until player clicks somewhere on the layout? It's still not a great solution. Is it possible to add "Set unfocused" action to Slider Bar?

**Comment by AshleyScirra** [comment]
Why would you want to do that? It's automatically handled like it was in the C2 runtime.

**Comment by dop2000** [comment]
I'm not talking about TextBox, TextBox should of course retain focus and block keyboard events. 

But the Slider Bar should not keep focus, or at least there should be a way to unfocus it.
Just last week I was developing a drawing application. There was a bunch of slider bars to control line width, zoom etc. I spent a lot of time trying to make keyboard shortcuts to work correctly after changing sliders. 
You change some setting with a slider, you don't like the result and immediately press Ctrl-Z to undo, but it doesn't work! Even when this is fixed in the next beta, I can't ask users to click anywhere on the screen before that can undo, it's counter-intuitive and not user friendly.
"Set unfocused" action will be a solution here.

By the way, "Set unfocused" is not working with checkboxes. It works in C2, but not in C3.

**Comment by AshleyScirra** [comment]
This is one of the times it becomes apparent Construct is designed for games, not applications. For games this approach normally suffices. Also all form controls are treated the same, since keyboard shortcuts generally should be handled by the form control instead of the game - for example you can nudge a slider bar with the arrow keys, and so arrow keys should not control the player in a game while they're being used to nudge the slider bar. So it's currently by design.

**Comment by dop2000** [comment]
@AshleyScirra What about various tests, quizzes, level/map builders, puzzle builders, kids drawing/doodling apps? People are making these in Construct, I've seen probably hundreds of such projects. 
Besides, Form Controls are not suited for real games, there are too many problems with them - difficult to style, not possible to z-order, fade, scale etc.
Anyway, could you please add "Unfocus" action to the SliderBar? This will improve its usability. I posted the idea:
https://construct3.ideas.aha.io/ideas/C3-I-1418
