### ISSUE TITLE
Desktop build crashes on preview with some projects

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4524]
## Problem description

With many old projects which were working fine in previous versions, now in r234 the Desktop App crashes on preview.

## Attach a .c3p

https://www.dropbox.com/s/u7eux0diam71k75/Crashing.c3p?dl=0

## Steps to reproduce

Run in the Desktop app.

## Observed result

The whole program closes immediately.

## More details

I tried re-installing the latest NWJS version 0.51.0, performing Storage cleanup, logging out and back in, clearing cache in Chrome. 
Please advise if there is anything else I should do.

**Affected browsers/platforms:** Desktop build

**First affected release:** r234

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.51.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@62f83a7521ae1f32e563795732dff0c9da1b660d) NWjs/0.51.0 (like Chrome/88.0.4324.96)
C3 release: r234 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 62 gb
Storage usage (approx): 39 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by avatar45D** [comment]
In addition to the problem Also in 234 release: Now if the project is saved as a script type - classic, then when you reopen it, the constructor it will still change to script type - module. (Desktop version Construct 234 NW 0.51)

**Comment by dop2000** [comment]
Can confirm this is related to scripts type setting. If I change it to Classic, the project attached in this bug report runs without crashing.

**Comment by avatar45D** [comment]
> Can confirm this is related to scripts type setting. If I change it to Classic, the project attached in this bug report runs without crashing.
> I don't understand how this matters, there are no scripts in the project.
Yes, it should work, you don't have any plugins. I had an error, exactly the same, but after a total removal of everything related to chrome (including google) and reinstallation, the error went away
But saving a project with a classic script type still does not work for me. when opening a project, it constantly changes to the type - module
For example, a plugin with encryption does not work for me when using the script type module. But I already have applications that need to be served with it.

Hopefully Ashley will fix the save so you don't have to change the project every time. And he will be able to tell what is wrong with the desktop version

**Comment by AshleyScirra** [comment]
I'll look in to it, but FYI if the whole app crashes that's generally an NW.js bug, not an issue with Construct, so it will probably have to be filed and fixed with the NW.js developers.

**Comment by dop2000** [comment]
@Ashley Yes, the whole editor crashes, but only when script mode is set to Module, even when there are no addons and no scripts in the project. This happened about a dozen times to me today. 
Thanks for looking into it.

**Comment by dop2000** [comment]
This appears to be fixed in r234.2 ! It's too early to tell, C3 updated only a few minutes ago, but the preview now seems to work with "Module" setting.

**Comment by AshleyScirra** [comment]
r234.2 did not change anything at all other than the configuration for Google Drive.

**Comment by dop2000** [comment]
> r234.2 did not change anything at all other than the configuration for Google Drive. Maybe it's sporadic?

Alshey, I don't know what to say. I can still reproduce this issue 100%:
in r234 with Module setting all projects crash, even the official templates.
In r234.2 with Module setting projects work fine, however with Classic the preview now gets stuck in black screen. Here is a short video:
https://youtu.be/NEe6EjI8b18

It may be something with my setup, but I've reinstalled nwjs several times, performed full Storage Cleanup many times, cleared cache in Chrome. Is there anything else I can do other than wiping the entire hard drive?

**Comment by avishaymizrav** [comment]
I've been getting these domside.js error message with Classic JS too, since r234 till r236.
I couldn't manage to pin down what is causing this so I'm using r233 for now.

**Comment by AshleyScirra** [comment]
I could not reproduce the originally reported issue (crash on preview) in the latest stable release with NW.js 0.51.1.

The error involving using "Classic" scripts is a different problem and so ought to go in its own report, but I could reproduce it in the latest stable release. However it seems to work in the latest beta release, so it appears to be something we've already fixed. Since there does not appear to be an active problem here, closing this issue - if you still have trouble please file a new issue following all the guidelines (including testing the latest beta and latest NW.js).
