### ISSUE TITLE
Saving/Loading hierarchies still not working in r307

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6041]
## Problem description

When loading saved game with complex hierarchies, there are errors in console log, some objects are resized or misplaced.

## Attach a .c3p

https://www.dropbox.com/s/9sftawq95t2iiv5/HierarchySaving3.c3p?dl=0

## Steps to reproduce

1. Click SAVE GAME
2. Click LOAD CHECKPOINT

## Observed result

Yellow button on top moves and resizes after loading. Some texts are misplaced.
If you click load again, it becomes even worse.

Error in the console log:

![image](https://user-images.githubusercontent.com/36763350/187018432-f9b4fd95-672e-4044-949e-6213f5b4943d.png)

I also get a different error message in the main game project, but I can't reproduce it in demo:

![image](https://user-images.githubusercontent.com/36763350/187018412-c5612549-c62e-4a32-a7c5-dec1608dcdcd.png)

Sorry for the messy demo project, but these errors seem to happen only with multiple complex hierarchies.
When I remove most of the hierarchy connections, the errors go away. But some objects are still misplaced and resized.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r307 (beta)
Browser: Chrome 104.0.5112.102
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 222 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Should be fixed in the next beta along with the previous related issues.

**Comment by MihaMS** [comment]
Hey guys, looks like you not fix this in r308! In the same example file - click more than once on LOAD CHECKPOINT and you will see jumping buttons! @DiegoScirra @AshleyScirra 

https://user-images.githubusercontent.com/23280578/187673010-dd312605-73f0-409c-a98a-4c530c6d6509.mp4

my bug also still present in r308 but behaves now a bit differently than in r307... 
https://github.com/Scirra/Construct-3-bugs/issues/6050

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines. It's impossible to help without a project file.

**Comment by dop2000** [comment]
> Please file a new issue following all the guidelines. It's impossible to help without a project file.

@AshleyScirra
It's the same demo project. Can confirm - loading the game state more than once breaks the hierarchy again..

**Comment by AshleyScirra** [comment]
@DiegoScirra - it does look like this isn't really fixed - save then repeatedly load and it sometimes comes back differently.
