### ISSUE TITLE
Saving file corrupts my file where constuct gives an "expected array" error and can't save any new work

### ISSUE THREAD

**Issue by drexegar** [Scirra/Construct-3-bugs#744]
## Problem description

When I successfully save my file on r50, I cannot save it again, instead I get an pop up error "expected array" and then construct 3 hangs on archieving

## Attach a .c3p

https://drive.google.com/file/d/0ByybatBADJBNQVZobHVHTHA2TlU/view?usp=sharing

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Use my file and save it
2. Construct 3 will give an "expected array" error
3. Construct will hang on archieving the file
4. If you try to save a new file you will get a blank 0k file

## Observed result

*What do you see happen?*
My game cannot save losing any work that I have done

## Expected result

*What did you expect to happen instead?*
My file to be save succesfully

## Affected browsers

* Chrome: yes
Havent tested others.

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

NOTES:
There must be something in the file r50 does not like, and this is an earlier version of my app which the problem still happens so its not something I recently added, its definitely r50 that does not like something that is in the file.

This does not happen with a newly saved blank file either.

I ALSO NOTICE YOU CAN SAVE SUCCESSFULLY MANY TIMES UNTIL YOU RESTART CONSTRUCT 3 r50.

**Comment by el3um4s** [comment]
happens to me on chrome too

**Comment by JeFawk** [comment]
same

**Comment by hansonbrody** [comment]
Same problem. Added a new issue before I saw this, maybe that'll help get it fixed!

**Comment by cihanyakar** [comment]
Duplicate #743 , I wrote a workaround there.

**Comment by DiegoScirra** [comment]
Fixed in r51.

**Comment by shortercode** [comment]
Think we'll keep this bug open until the next release comes out, so we don't get any more duplicates of this

**Comment by drexegar** [comment]
Ok well I removed those unwanted files from the work around, and that fixed the problem. So saving is not an issue anymore.

**Comment by drexegar** [comment]
SORRY I UPLOADED WRONG FILE HERE THE LATEST FILE SAVED IN r50
https://drive.google.com/file/d/0ByybatBADJBNQVZobHVHTHA2TlU/view?usp=sharing

I still get a corrupted APK with this one, I will also update the post
